#!/usr/bin/env node
/**
 * Write one printable sheet page and one answer-key page per lesson, from the
 * data that scripts/extract_checks.js pulled out of the lessons.
 *
 * The pages are three-line stubs — all the content comes from checks.json at
 * render time, so they can never drift from the lessons. They live under
 * src/pages/ (not docs/) so they get no sidebar, no breadcrumb and no prev/next
 * navigation: a sheet, not a lesson.
 *
 * Run by `npm start` / `npm run build` automatically (prestart / prebuild).
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CHECKS = require(path.join(ROOT, 'src', 'data', 'checks.json'));
const OUT_ROOT = path.join(ROOT, 'src', 'pages', 'checks');

const BANNER = '{/* GENERATED by scripts/generate_quiz_pages.js — do not edit. */}';

function page(id, {answers}) {
  const lesson = CHECKS[id];
  const title = `${lesson.lessonTitle} — Knowledge Checks${answers ? ' (Answer Key)' : ''}`;
  return `---
title: "${title.replace(/"/g, "'")}"
description: "${lesson.moduleTitle} — printable knowledge checks${answers ? ', answer key' : ''}"
hide_table_of_contents: true
---

${BANNER}

<QuizSheet id="${id}"${answers ? ' answers' : ''} />
`;
}

function main() {
  // Start clean so a renamed or deleted lesson doesn't leave a stale sheet.
  fs.rmSync(OUT_ROOT, {recursive: true, force: true});

  let n = 0;
  for (const id of Object.keys(CHECKS)) {
    const dir = path.join(OUT_ROOT, path.dirname(id));
    fs.mkdirSync(dir, {recursive: true});
    const base = path.basename(id);
    fs.writeFileSync(path.join(dir, `${base}.mdx`), page(id, {answers: false}));
    fs.writeFileSync(path.join(dir, `${base}-key.mdx`), page(id, {answers: true}));
    n += 2;
  }
  fs.writeFileSync(
    path.join(OUT_ROOT, 'index.mdx'),
    `---
title: "Printable Knowledge Checks"
description: "Every lesson's knowledge checks as a printable handout, with answer keys"
hide_table_of_contents: true
---

${BANNER}

<QuizIndex />
`
  );
  console.log(`generate_quiz_pages: ${n + 1} pages → src/pages/checks/`);
}

main();
